### ISSUE TITLE
Ability to unfreeze collection after `.freeze()` method is called

### ISSUE THREAD

**Issue by Gr1N** [aio-libs/frozenlist#103]
## Long story short

Hi,

In some cases, I need to unfreeze my collection, make some mutation, and freeze it again. With the current API of the collection, there is no way to do that without collection recreation.

I can submit a PR with changes I want to see in the library, just let me know if my proposal is acceptable.

## Expected behaviour

```python
l = FrozenList()
l.append(1)
l.freeze()

l.unfreeze()
l.append(2)
```

## Actual behaviour

```python
l = FrozenList()
l.append(1)
l.freeze()

l = FrozenList()
l.append(1)
l.append(2)
```

## Steps to reproduce

Described in the examples above.

**Comment by mjpieters** [comment]
> With the current API of the collection, there is no way to do that without collection recreation.

That's deliberate. Once frozen, it it is an immutable collection, like a tuple or a frozenset. Other code can then rely on the sequence to never change; it can be used in concurrent code.

You can't create an `unfreeze()` method without breaking this. Instead, create a new `FrozenList()` that is a copy of the old, frozen `FrozenList()` instance, and replace the reference. That way existing references to the frozen copy can complete their work, then later on grab a reference to the new object.
