### ISSUE TITLE
PyPI access

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/frozenlist#159]
@mjpieters please add me ( andrew.svetlov ) to frozenlist and aiosignals projects on PyPI.

This blocks me from publishing a new version with Python 3.8-3.9 support.

Thanks.

**Comment by mjpieters** [comment]
Done and done.

**Comment by asvetlov** [comment]
Very fast! Thank you!

**Comment by asvetlov** [comment]
Sorry, I need "Manage" access for generation a new token for PyPI deployment. 
I don't like passing my PyPI credentials to GitHub bot but prefer token-based auth with very restricted rights (release upload only).

**Comment by asvetlov** [comment]
Hmm, I'm able to generate token (PyPI GUI is tricky a little).
But wider rights are still desirable ;)

**Comment by mjpieters** [comment]
>  But wider rights are still desirable ;)

Alrighty, since you asked so nicely. 😛
