### ISSUE TITLE
CI misconfigure

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/frozenlist#171]
CI build on push-tag cancels itself.

From my understanding, `skipduplicate-actions` at https://github.com/aio-libs/frozenlist/blob/master/.github/workflows/ci.yml#L26 have false-positive for tag pushing, it prevents not only tests but the deployment also.

@mjpieters we need to fix this.
Sorry, I tried to repair the broken workflow but failed.  `should_skip` and `test-summary` looks overcomplicated for me :(

**Comment by mjpieters** [comment]
Okidoki, sorry if this caused headaches!
