### ISSUE TITLE
Where is  frozenlist/_frozenlist.c

### ISSUE THREAD

**Issue by papoteur-mga** [aio-libs/frozenlist#298]
## Long story short
gcc: fatal error: frozenlist/_frozenlist.c: No such file or directory
## Expected behaviour
Build success
## Actual behaviour
I have loaded the repository in zip format, unzipped and tried to build with
python3 setup.py build
It fails because frozenlist/_frozenlist.c is not found. 

## Your environment
Mageia 8

**Comment by papoteur-mga** [comment]
In fact, this is the same issue as #296
`FROZENLIST_NO_EXTENSIONS=1  python3 setup.py build`
is successful.

**Comment by mjpieters** [comment]
Yes, Cython is required but it's not been set up to run Cython automatically. We'll fix that in the other issue.

In the meantime, you can run:

```
pip install cython==0.29.26
cython -3 -o frozenlist/_frozenlist.c frozenlist/_frozenlist.pyx -I frozenlist
```

to generate the .c file. Or run `make cythonize`, but that includes a few more development-specific packages.

**Comment by mjpieters** [comment]
Note that you should really just grab the source release for this project; the releases tab has release assets that include a source .tgz. File.

The release process generates the .c files needed.

**Comment by papoteur-mga** [comment]
Thanks,
I added
`python3  -m cython -3 frozenlist/*.pyx -I frozenlist`
in my process.
