### ISSUE TITLE
RTD access + housekeeping

### ISSUE THREAD

**Issue by webknjaz** [aio-libs/frozenlist#326]
@mjpieters I see you're the only one listed as a maintainer on RTD. I wanted to wire up the `frozenlist.aio-libs.org` subdomain (it's already configured on the DNS side) and re-toggle PR builds (this setting seems to be stuck, the checkbox needs to be turned off and on again).
Maybe you could add other people there to deal with the bus factor? Or just perform these activities yourself, please.

**Comment by webknjaz** [comment]
@mjpieters ^

**Comment by mjpieters** [comment]
@webknjaz sorry about this; I added you and @asvetlov to the list of maintainers now.

**Comment by mjpieters** [comment]
I also added the domain now, and am doing the same for aiosignal.

**Comment by webknjaz** [comment]
Thanks! I've handled that CNAME too.
