### ISSUE TITLE
Compiling frozenlist error: 'frozenlist/_frozenlist.c': No such file or directory

### ISSUE THREAD

**Issue by mniesen** [aio-libs/frozenlist#349]
I tried to compile the frozenlist python package and it gave me this error.
```c1: fatal error C1083: Cannot open source file: 'frozenlist/_frozenlist.c': No such file or directory```
I don't see a file named _frozenlist.c in the frozenlist folder.

I got this error when using the command ```py setup.py build```
I am using Windows 10 with Microsoft C++ Build Tools

**Comment by mjpieters** [comment]
You are missing the cython build dependency, which generates the `frozenlist/_frozenlist.c` file from the .pyx file. It's easiest using make:

```
make cythonize
pip install .
```
