### ISSUE TITLE
Request for pure python wheel

### ISSUE THREAD

**Issue by stevapple** [aio-libs/frozenlist#513]
## Long story short

`frozenlist` already supports pure Python mode (with no `frozenlist._frozenlist` extension), but the wheel is not available on PyPI. This blocks cross-platform usages like `micropip`.

If possible, we can build and upload a `frozenlist-1.4.0-py3-none-any.whl` to PyPI.

## Expected behaviour

There's a pure Python wheel for downloading on PyPI.

**Comment by mjpieters** [comment]
The installer already accounts for this; `setup.py` only attempts to install extension modules when using cpython. Is there any reason why micropip **must** use a downloadable wheel and can't fall back to the tarball?

**Comment by mjpieters** [comment]
Last but not least, if we were to provide a universal non-binary wheel, then any platform we do support the C-extension for but don't have a wheel for would end up with the non-binary version and not with a locally compiled wheel installed from the tarball.

That's not a desirable outcome, so I'm going to close this issue.
