### ISSUE TITLE
(🎁) Build wheels for 3.12

### ISSUE THREAD

**Issue by KotlinIsland** [aio-libs/frozenlist#541]

**Comment by RNarayan73** [comment]
Any update on this request?

**Comment by fenchu** [comment]
There is no `frozenlist/_frozenlist.c`:
```
c1: fatal error C1083: Cannot open source file: 'frozenlist/_frozenlist.c': No such file or directory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
```

**Comment by webknjaz** [comment]
v1.4.1 now ships said wheels:
- [change log](https://frozenlist.aio-libs.org/en/v1.4.1/changes/)
- [PyPI](https://pypi.org/project/frozenlist/1.4.1/)
- [Sigstore signatures](https://github.com/aio-libs/frozenlist/releases/tag/v1.4.1)
