### ISSUE TITLE
installing via poetry throws error, can't assess keyring.

### ISSUE THREAD

**Issue by gegoxaren** [aio-libs/frozenlist#581]
## Long story short

Trying to import `frozenlist` via `poetry` on headless system results in errors. 

REF:
https://gitlab.com/imbev/matrix-rss-bridge/-/issues/3

## Expected behaviour

`poetry` not throwing an error when installing on a system without X installed.

## Actual behaviour

`poetry` throws an error that it can't access the keying.

## Steps to reproduce

on a headless system, logged in as root:
```
# cd project_name
# poetry add frozenlist
# poetry install
```

## Your environment

```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm
# uname -a
Linux eeepc-debian 6.1.0-18-686 #1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01) i686 GNU/Linux
# python3 --version
Python 3.11.2
# poetry --version
Poetry (version 1.3.2)
```

**Comment by webknjaz** [comment]
There's nothing related to this project in the issue. Take it up with Poetry.
