### ISSUE TITLE
prebuilt speedups wheel for python 3.13

### ISSUE THREAD

**Issue by asottile-sentry** [aio-libs/frozenlist#608]
(sorry skipping the template)

noticed that the build is enabled for 3.13 (#595) but I'm still getting a purelib wheel from pypi:

```console
$ ./venv313/bin/pip install frozenlist
Collecting frozenlist
  Downloading frozenlist-1.4.1-py3-none-any.whl.metadata (12 kB)
Downloading frozenlist-1.4.1-py3-none-any.whl (11 kB)
Installing collected packages: frozenlist
Successfully installed frozenlist-1.4.1
```

**Comment by bdraco** [comment]
It looks like the library needs a new release

**Comment by bdraco** [comment]
https://github.com/aio-libs/frozenlist/actions/runs/11473328151 in progress

I'm not sure I have permission to release the pypi step though for this repo so might have to wait a bit for someone with the right keys
